uza nasmedi kitabe pa dexnam
barumau/pandunia pull request #133
Opened 2021-02-02 22:37 UTC by jkunimune15

zayo, dexnam kitabu no autosamo.  me suja mome nova lole pa uza ci kanun:

- Use the pronunciation of the place in the local language.
- Modify letters to match the international spelling, if that pronunciation is historical or forbidden by the local language's phonotactics.
  - **Arhentina** -> **Argentina** (/g/ is the historical Latin pronunciation)
  - **Ostrailia** -> **Australia** (/au/ and /aː/ are the historical Latin pronunciations)
  - **Lihtenxtain** -> **Lihtenstain** (/s/ is forbidden by German phonotactics)
- Replace any suffix that means "land" and is dropped in the demonym with **-ia**.
  - **Magyarorsag** -> **Magyaria** (**-orsag** means "land")
  - **Kanada** stays the same (**-a** does not mean "land")
  - **Island** stays the same (**-land** is not dropped in the demonym)
- Remove any prefix or circumfix that means "land" and is not present in the demonym.
  - **Bocwana** -> **Cwana** (**bo-** means "land")
  - **Sakartvelo** -> **Kartvel** (**sa- -o**) means "land")
- Remove any articles, as well as English, French, and Dutch plural suffixes.
  - **Alurdun** -> **Urdun** (**al-** means "the")
  - **El Salvador** -> **Salvador** (**el** means "the")
  - **Seyxelz** -> **Seyxel** (**-z** means "many")
- Use **-ia** if the official English name with **-ia**.
  - **Bosna** -> **Bosnia**
  - **Osteraih** -> **Ostria**
  - **Jayer** -> **Jayeria**
- Add epenthesis so that no syllable starts with more than two consonants or ends with more than one soft consonant.
  - **Nederland** -> **Nederlande**
  - **Polske** okeyi
  - **Svenia** okeyi

2021-02-03 13:05 UTC, barumau commented on pandunia-loge.csv
> +Xkip:ia|Xkipia|desh|AL||Albania||Albania||||||||||||||Albania|Albania
hem... pani jan no abla loga le. aslo name sa Shqipëri (shqip +‎ -ëri) /ʃcipəˈɾia/, /ʃcɕipəˈɾia/. me fikra Cipia o Xipia sa max izi.

2021-02-03 13:06 UTC, barumau commented on pandunia-loge.csv
> +Xri Lanka|Xri Lanka|desh|LK||Sri Lanka (Ceylon)||Sri Lanka||||||||||||||Sri Lanka|Sri Lanka
max ka kunani! me fikra "Xri" mena "onori", e dexname no nida le.

2021-02-03 13:13 UTC, barumau commented on pandunia-loge.csv
> +Un.it:i Desh: D:a Amerike (UDA)|Uniti Desh Da Amerike (UDA)|desh|US||United States of America (USA)||Estados Unidos de América||||||||||||||Yhdysvallat (ns. Amerikka)|Stany Zjednoczone Ameryki
boni name! eska ali UDA jan okeya le?

Desh →Dex.

2021-02-03 13:14 UTC, barumau commented on pandunia-loge.csv
> +Turkmenia|Turkmenia|desh|TM||Turkmenistan||Turkmenistán||||||||||||||Turkmenistan|Turkmenistan
me vola uza -o-, sabu le si max izo logabli e le xowa fen da ci nam : turk + men.

2021-02-03 13:17 UTC, barumau commented on pandunia-loge.csv
> +Taibey|taibey||||Taipei||Taipei||||||||||||||Taipei|Tajpej
ratibi nam sa sahi. no anmema vidabli nam!

2021-02-03 13:20 UTC, barumau commented on pandunia-loge.csv
> +suomi:i|suomii||||Finnish||finés|||||||||||||finna|suomalainen|fiński
mul da ci loge sa suom-. Suom-i (Finland), suom-en kieli (Finnish language), suom-alainen (Finnish).

me sa suomi jan e me vola uza Suomia (o Suomi dex) e suomi.

2021-02-03 13:22 UTC, barumau commented on pandunia-loge.csv
> +Sud:i Georg:ia w:a Sud:i Sandwic:e nes:ia|Sudi Georgia e Sudi Sandwice nesia|desh|GS||South Georgia and the South Sandwich Islands||Georgias del Sur y Sándwich del Sur|||||||||||||||Wyspy Georgia Poł
eska te vero vola loga /ge.or.gi.a/?

2021-02-03 13:25 UTC, barumau commented on pandunia-loge.csv
> +Sud:i Georg:ia w:a Sud:i Sandwic:e nes:ia|Sudi Georgia e Sudi Sandwice nesia|desh|GS||South Georgia and the South Sandwich Islands||Georgias del Sur y Sándwich del Sur|||||||||||||||Wyspy Georgia Poł
uza "e" sa loke da "w:a".

2021-02-03 13:27 UTC, barumau commented on pandunia-loge.csv
> +Sud:i Afrik:e|Sudi Afrike|desh|ZA||South Africa||Sudáfrica||||||||||||||Etelä-Afrikka|Południowa Afryka
eska le sa dex o aria? me suja "Sudafrike" sa dex e "sudi Afrike" sa aria.

2021-02-03 13:31 UTC, jkunimune15 commented on pandunia-loge.csv
> +Xri Lanka|Xri Lanka|desh|LK||Sri Lanka (Ceylon)||Sri Lanka||||||||||||||Sri Lanka|Sri Lanka
a, me paso no ablu eureka men da "xri".  ago da ce, me wilo kita le.

2021-02-03 13:47 UTC, jkunimune15 commented on pandunia-loge.csv
> +Sud:i Georg:ia w:a Sud:i Sandwic:e nes:ia|Sudi Georgia e Sudi Sandwice nesia|desh|GS||South Georgia and the South Sandwich Islands||Georgias del Sur y Sándwich del Sur|||||||||||||||Wyspy Georgia Poł
logasle purani heleni _Γεώργιος_, /georgos/, e histori fon konformu pa zayi kitabe.  me raya le sami da "au" va "Australia" e "g" va "Argentina".

2021-02-03 13:49 UTC, jkunimune15 commented on pandunia-loge.csv
> +Sud:i Afrik:e|Sudi Afrike|desh|ZA||South Africa||Sudáfrica||||||||||||||Etelä-Afrikka|Południowa Afryka
a, razonu.

"sudi " + dex du nam = dex du nam  
"sudi " + aria du nam = aria du nam  
"sudo" + aria du nam = dex du nam

2021-02-03 13:50 UTC, barumau requested changes

2021-02-03 13:50 UTC, barumau commented on pandunia-loge.csv
> +Somalilande|Somalilande|desh|||Somaliland||Solamilandia||||||||||||||Somalimaa|Somaliland
nasnam sa somali, asaro dexnam sa Somaldex!

2021-02-03 13:50 UTC, barumau commented on pandunia-loge.csv
> +Siera: Leon:|Siera Leon|desh|SL||Sierra Leone||Sierra Leona||||||||||||||Sierra Leone|Sierra Leone
nam sa "Salone" va krio bax. ("Krio is the most widely spoken language across Sierra Leone, spoken by 97% of the country's population.")

2021-02-03 13:50 UTC, barumau commented on pandunia-loge.csv
> +Seyxel nesia|Seyxel nesia|desh|SC||Seychelles||Seychelles||||||||||||||Seychellit|Seszele
Sexel du nam laya ja fransi politiker Jean Moreau de Séchelles.

2021-02-03 13:50 UTC, barumau commented on pandunia-loge.csv
> +Nistrov:ia|Nistrovia|desh|||Transnistria||Transnistria (Cisdniéster)||||||||||||||Transdnistria|Naddniestrze
nade du nam sa Dniestr. me fikra Nistria sa boni nam.

2021-02-03 13:50 UTC, barumau commented on pandunia-loge.csv
> +Niger:ia|Nigeria|desh|NG||Nigeria||Nigeria|||||||||||||Niĝerio|Nigeria|Nigeria
Hausa : Nijeriya, Najeriya
Yoruba : Nàìjíríà
Igbo : Naigeria, Naìjíríyà
Nigerian Pidgin English: Naijiria

2021-02-03 13:50 UTC, barumau commented on pandunia-loge.csv
> +Niger:|Niger:|desh|NE||Niger||Níger|||||||||||||Niĝero|Niger|Niger
aga mome uza "Nigeria" e "Niger", mome no abla sava men da "nigeri". maxo me fikra pandunia bono uza sami sondomutokanun va dexnam ka va ali loge.

2021-02-03 13:50 UTC, barumau commented on pandunia-loge.csv
> +Misr:e|Misre|desh|EG|ara:(miṣr), tur:Mısır, swa:Misri, hin:मिस्र (misra), ben:মিশর (miśôr)|Egypt|Égypte|Egipto|Egipto (Egito)|Египет||埃及|エジプト|이집트|Ai Cập|मिस्र|মিশর|Mesir|Misri|Mısır|Egipto|Egypti|Egi
-e no sa fen da asli loge. me vola uza Misria.

2021-02-03 13:50 UTC, barumau commented on pandunia-loge.csv
> +luteristia|lutheristia||||Lutheranism|luthéranisme|luteranismo|luteranismo|лютера́нство||||||||||||luterilaisuus|luteranizm
okey, a luteristia mena "robber-ism" :D

2021-02-03 13:55 UTC, jkunimune15 commented on pandunia-loge.csv
> +suomi:i|suomii||||Finnish||finés|||||||||||||finna|suomalainen|fiński
multo bon. me buda sifloge du "-i" multo malo rupu va logomul finu sa jungofon.  me wilo muta "suomi:i" pa "suom:i", e me wilo max muta "roma:i imper:ia" pa "roma: imper:ia" e "lietuva:i" pa "lietuva: bax".

2021-02-03 14:00 UTC, jkunimune15 commented on pandunia-loge.csv
> +Xkip:ia|Xkipia|desh|AL||Albania||Albania||||||||||||||Albania|Albania
bon tes.  me no jana maxim bon punte medo da fonablia e aslosamia.  rupu sa loge da xuru ya xkV, xrV, e skV max kunani ga bas.  me wilo muta ci nam retro.

2021-02-03 19:48 UTC, barumau commented on pandunia-loge.csv
> +suomi:i|suomii||||Finnish||finés|||||||||||||finna|suomalainen|fiński
okey :)

2021-02-03 19:51 UTC, barumau commented on pandunia-loge.csv
> +Sud:i Georg:ia w:a Sud:i Sandwic:e nes:ia|Sudi Georgia e Sudi Sandwice nesia|desh|GS||South Georgia and the South Sandwich Islands||Georgias del Sur y Sándwich del Sur|||||||||||||||Wyspy Georgia Poł
okey. me no tena forti ray tema ci nam.

2021-02-03 19:53 UTC, barumau commented on pandunia-loge.csv
> +Sud:i Afrik:e|Sudi Afrike|desh|ZA||South Africa||Sudáfrica||||||||||||||Etelä-Afrikka|Południowa Afryka
ye. :+1:

2021-02-03 20:51 UTC, jkunimune15 commented on pandunia-loge.csv
> +luteristia|lutheristia||||Lutheranism|luthéranisme|luteranismo|luteranismo|лютера́нство||||||||||||luterilaisuus|luteranizm
ye... me no sava bon daw pa bona ci. "luther" rupu bizari pa me. va doici, no fonu /lut.her/ o /lut.xer/.

ablo kitaba le sa "luteistia", o "lutaristia", o "martinluteristia"?

2021-02-03 20:51 UTC, jkunimune15 commented on pandunia-loge.csv
> +Misr:e|Misre|desh|EG|ara:(miṣr), tur:Mısır, swa:Misri, hin:मिस्र (misra), ben:মিশর (miśôr)|Egypt|Égypte|Egipto|Egipto (Egito)|Египет||埃及|エジプト|이집트|Ai Cập|मिस्र|মিশর|Mesir|Misri|Mısır|Egipto|Egypti|Egi
ci razonabli. me wilo muta le, e muta "Nederlande" e "Cade" pa "Nederlandia" e "Cadia".

2021-02-03 20:54 UTC, jkunimune15 commented on pandunia-loge.csv
> +Niger:|Niger:|desh|NE||Niger||Níger|||||||||||||Niĝero|Niger|Niger
a, bon tes. va engli, jannam sa "Nigerian" e "Nigerien", a le polo samsifi. polo mal sistem.

ago da Nijer kitabu sa "Nijer", te raya mome xudu uza "Arhentina" e "Onduras"?

2021-02-03 20:55 UTC, barumau commented on pandunia-loge.csv
> +luteristia|lutheristia||||Lutheranism|luthéranisme|luteranismo|luteranismo|лютера́нство||||||||||||luterilaisuus|luteranizm
"martinluteristia" sa boni! :+1:

2021-02-03 20:55 UTC, barumau commented on pandunia-loge.csv
> +Misr:e|Misre|desh|EG|ara:(miṣr), tur:Mısır, swa:Misri, hin:मिस्र (misra), ben:মিশর (miśôr)|Egypt|Égypte|Egipto|Egipto (Egito)|Египет||埃及|エジプト|이집트|Ai Cập|मिस्र|মিশর|Mesir|Misri|Mısır|Egipto|Egypti|Egi
bon!

2021-02-04 02:55 UTC, jkunimune15 commented
me nova tirplize ya ti piping. zayo, te fikra ke?

2021-02-04 08:12 UTC, barumau commented on pandunia-loge.csv
> +Xri Lanka|Xri Lanka|desh|LK||Sri Lanka (Ceylon)||Sri Lanka||||||||||||||Sri Lanka|Sri Lanka
OK

2021-02-04 08:32 UTC, barumau commented on pandunia-loge.csv
> +Danmark:ia|Danmarkia|desh|DK||Denmark||Dinamarca|||||||||||||Danio|Tanska|Dania
me suja Dania sabu "mark" mena maidan va dani bax e kenar va lawi eskandinavi bax. bax sa "dansk" e jan sa "dansker" va dani bax.

2021-02-04 08:37 UTC, barumau approved these changes
uniko un lili galte, a mi se wilo muta Danmarkia pa Dania.

polo danke! :)

2021-02-04 08:37 UTC, merged